updated the shell script and ci yml

diff --git a/.github/workflows/snwflk-dbt-ci.yml b/.github/workflows/snwflk-dbt-ci.yml
--- a/.github/workflows/snwflk-dbt-ci.yml
+++ b/.github/workflows/snwflk-dbt-ci.yml
@@ -20,82 +20,86 @@ jobs:
               with:
                 python-version: '3.9'
     
-            # - name: Make Script Executable
-            #   run: chmod +x scritps/setup_dbt_env.sh
+            - name: Make Script Executable
+              run: chmod +x scritps/setup_dbt_env.sh
             
-            # - name: Create Python Virtual Environment and install DBT
-            #   run: bash /scritps/setup_dbt_env.sh
-            #   env:
-            #     SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
-            #     SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
-            #     SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
-            #     SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
-            #     SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
-            #     SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
-            #     SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
-            #     SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
+            - name: Create Python Virtual Environment and install DBT
+              run: bash /scritps/setup_dbt_env.sh
+              env:
+                SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
+                SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
+                SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
+                SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
+                SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
+                SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
+                SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
             
-            - name: Running the shell script
-              shell: bash
-              run: |
-                #!/bin/bash
-                ###########exit immediately if a command exits with a non-zero status
-                set -e
-                ###########fail the script if any command in a pipeline fails
-                set -o pipefail
-                echo "Starting DBT Setup script"
-                if ! command -v python &> /dev/null; then
-                    echo "Python is not installed. Please install Python and try again."
-                    exit 1
-                else
-                    echo "Python is installed. $(python --version)"
-                    python -m venv dbt-env
-                fi
-                if [ -d "dbt-env" ]; then
-                    echo "Virtual environment created successfully."
-                else
-                    echo "Failed to create virtual environment."
-                    exit 1
-                fi
-                if ! command -v dbt &> /dev/null; then
-                    echo "DBT is not installed. Installing DBT..."
-                    source dbt-env/bin/activate
-                    pip install dbt-snowflake
-                else
-                    echo "DBT is already installed."
-                fi
-                if ! command -v dbt &> /dev/null; then
-                    echo "DBT installation failed. Please check the installation process."
-                    exit 1
-                else
-                    echo "DBT is installed successfully. $(dbt --version)"
-                fi
-
-                mkdir -p ~/.dbt
-                echo "pass_snwflk_demo:" >> ~/.dbt/profiles.yml
-                echo "  target: dev" >> ~/.dbt/profiles.yml
-                echo "  outputs:" >> ~/.dbt/profiles.yml
-                echo "    dev:" >> ~/.dbt/profiles.yml
-                echo "      type: snowflake" >> ~/.dbt/profiles.yml
-                echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
-                echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
-                echo "      role: ${{ secrets.SNOWFLAKE_ROLE }}" >> ~/.dbt/profiles.yml
-                echo "      database: ${{ secrets.SNOWFLAKE_DATABASE }}" >> ~/.dbt/profiles.yml
-                echo "      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> ~/.dbt/profiles.yml
-                echo "      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}" >> ~/.dbt/profiles.yml
-                echo "      private_key: |" >> ~/.dbt/profiles.yml
-                echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}" | sed 's/^/        /' >> ~/.dbt/profiles.yml
-                echo "      threads: 1" >> ~/.dbt/profiles.yml
-                echo "      client_session_keep_alive: False" >> ~/.dbt/profiles.yml
-
             - name: Validate DBT Configuration
               run: |
                 source dbt-env/bin/activate
                 dbt debug --profiles-dir ~/.dbt --target dev
+                            
+            # - name: Running the shell script
+            #   shell: bash
+            #   run: |
+            #     #!/bin/bash
+            #     ###########exit immediately if a command exits with a non-zero status
+            #     set -e
+            #     ###########fail the script if any command in a pipeline fails
+            #     set -o pipefail
+            #     echo "Starting DBT Setup script"
+            #     if ! command -v python &> /dev/null; then
+            #         echo "Python is not installed. Please install Python and try again."
+            #         exit 1
+            #     else
+            #         echo "Python is installed. $(python --version)"
+            #         python -m venv dbt-env
+            #     fi
+            #     if [ -d "dbt-env" ]; then
+            #         echo "Virtual environment created successfully."
+            #     else
+            #         echo "Failed to create virtual environment."
+            #         exit 1
+            #     fi
+            #     if ! command -v dbt &> /dev/null; then
+            #         echo "DBT is not installed. Installing DBT..."
+            #         source dbt-env/bin/activate
+            #         pip install dbt-snowflake
+            #     else
+            #         echo "DBT is already installed."
+            #     fi
+            #     if ! command -v dbt &> /dev/null; then
+            #         echo "DBT installation failed. Please check the installation process."
+            #         exit 1
+            #     else
+            #         echo "DBT is installed successfully. $(dbt --version)"
+            #     fi
 
-            - name: List files in the repository
-              run: |
-               ls ${{ github.workspace }}
+            #     mkdir -p ~/.dbt
+            #     echo "pass_snwflk_demo:" >> ~/.dbt/profiles.yml
+            #     echo "  target: dev" >> ~/.dbt/profiles.yml
+            #     echo "  outputs:" >> ~/.dbt/profiles.yml
+            #     echo "    dev:" >> ~/.dbt/profiles.yml
+            #     echo "      type: snowflake" >> ~/.dbt/profiles.yml
+            #     echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
+            #     echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
+            #     echo "      role: ${{ secrets.SNOWFLAKE_ROLE }}" >> ~/.dbt/profiles.yml
+            #     echo "      database: ${{ secrets.SNOWFLAKE_DATABASE }}" >> ~/.dbt/profiles.yml
+            #     echo "      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> ~/.dbt/profiles.yml
+            #     echo "      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}" >> ~/.dbt/profiles.yml
+            #     echo "      private_key: |" >> ~/.dbt/profiles.yml
+            #     echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}" | sed 's/^/        /' >> ~/.dbt/profiles.yml
+            #     echo "      threads: 1" >> ~/.dbt/profiles.yml
+            #     echo "      client_session_keep_alive: False" >> ~/.dbt/profiles.yml
+
+            # - name: Validate DBT Configuration
+            #   run: |
+            #     source dbt-env/bin/activate
+            #     dbt debug --profiles-dir ~/.dbt --target dev
+
+            # - name: List files in the repository
+            #   run: |
+            #    ls ${{ github.workspace }}
               
             # - name: Run DBT model with debug
             #   run: |
